---
output:
  word_document:
    reference_docx: !expr system.file("rmarkdown/word-styles-reference.docx", package = "g4dbr")
---

```{r library, include=FALSE}
library(knitr)
```

```{r subchunkify, include=FALSE}
subchunkify <- function(g, fig_height=7, fig_width=5) {
  g_deparsed <- paste0(deparse(
    function() {g}
  ), collapse = '')
  
  sub_chunk <- paste0("
  `","``{r sub_chunk_", floor(runif(1) * 10000), ", fig.height=", fig_height, ", fig.width=", fig_width, ", echo=FALSE}",
  "\n(", 
    g_deparsed
    , ")()",
  "\n`","``
  ")
  
  cat(knitr::knit(text = knitr::knit_expand(text = sub_chunk), quiet = TRUE))
}
```


# Data

```{r selected.oligos, include=FALSE}
#Extract the selected oligonucleotides names to print as a comma separated string
if (length(selected.oligos.db()) > 1) { #if more than one oligo, then use plural
  selected.oligos <- paste("oligonucleotides", paste(selected.oligos.db()[1:length(selected.oligos.db())-1], collapse=", "), "and", selected.oligos.db()[length(selected.oligos.db())])
} else { #else use singular 
  selected.oligos <- paste("oligonucleotide", paste(selected.oligos.db(), collapse=", "))
}
```

This report was generated by *g4dbr* for the `r selected.oligos` on `r Sys.Date()`.

```{r title, include=FALSE}
#Document title takes selected oligonucleotides values
title_var <- paste(paste(selected.oligos.db(), collapse="/"), "report")
```

---
title: `r title_var`
author: g4dbr
date: `r Sys.Date()`
output:
  word_document:
    reference_docx: word-styles-reference.docx
---

```{r oligo.table, echo=FALSE, message=FALSE, warning=FALSE, paged.print=TRUE}
#table of oligonucleotides properties (pageable)
db.info <- db.info() %>%
  filter(oligo %in% selected.oligos.db()) %>% #only display selected oligos data
  select(c('oligo', 'sequence', 'submitted_by', 'depo.date', 'DOI'))

knitr::kable(db.info,
             caption = 'General oligonucleotide information',
             escape = F) #DOI parsed in HTML reports
```

# Figures

## CD

```{r CDplot, echo=FALSE, message=FALSE, warning=FALSE, dpi=600, fig.cap='CD spectra', fig.align='center', results='asis'}
pcd <- p.CD.db()
subchunkify(pcd, 3 * row.p.CD.db(), 7)
```


## 1H-NMR

```{r NMRplot, echo=FALSE, message=FALSE, warning=FALSE, dpi=600, fig.cap='1H NMR spectra', fig.align='center', results='asis'}
pnmr <- p.NMR.db()
subchunkify(pnmr, 3 * row.p.NMR.db(), 7)
```


## UV-melting

```{r UVplot.raw, echo=FALSE, message=FALSE, warning=FALSE, fig.width=5, dpi=600, fig.cap='Raw UV-melting plot', fig.align='center'}
p.UV.melting.db() + 
  theme(legend.position="bottom",
        legend.direction = "horizontal") +
  guides(colour=guide_legend(nrow=length(selected.oligos.db())))
```


```{r UVplot.fit, echo=FALSE, message=FALSE, warning=FALSE, fig.width=5, dpi=600, fig.cap='Folded fraction', fig.align='center'}
p.UV.fit.db() + 
  theme(legend.position="bottom",
        legend.direction = 'horizontal') +
  guides(colour=guide_legend(nrow=length(selected.oligos.db())))
```



```{r print.option, message=FALSE, warning=FALSE, include=FALSE}
#controls whether MS section is knitted or not based on the use of the plotMS button
if(input$plotMS.db == 0) {
  print.option <- FALSE
} else {
  print.option <- TRUE
}
```

```{r MS.header, echo=FALSE, eval= print.option}
#conditional MS section title
asis_output("## Native ESI-MS")
```

```{r MSplot, eval=print.option, echo=FALSE, fig.align='center', fig.cap='Folded fraction', message=FALSE, warning=FALSE, dpi=600, results='asis'}
pms <- p.MS.db() + 
  theme(legend.position="bottom",
        legend.direction = 'horizontal')
subchunkify(pms, 3 * row.p.MS.db(), 7)
```


