---
output:
  word_document:
    reference_docx: !expr system.file("rmarkdown/word-styles-reference.docx", package = "g4dbr")
---

```{r library, include=FALSE}
library(knitr)
```

```{r subchunkify, include=FALSE}
# allows figure sizing within r chunck
# modified from http://michaeljw.com/blog/post/subchunkify/
subchunkify <- function(g, cap=NULL, fig_height=7, fig_width=5) {
  #g argument is the object to plot
  #cap is the figure caption
  g_deparsed <- paste0(deparse( #deparse turns function() {g} into string that Knitr can interpret
    function() {g}
  ), collapse = '')
  
  sub_chunk <- paste0("
  `","``{r sub_chunk_", floor(runif(1) * 10000), #give the generated sub-chunk a unique name
  ", fig.height=", fig_height, ", fig.width=", fig_width, ", fig.cap=", cap, ", echo=FALSE, message=FALSE, warning=FALSE, fig.align='center', dpi = 300}",
  "\n(", 
  g_deparsed
  , ")()",
  "\n`","``
  ")
  
  #knitr::knit() compiles the generated sub-chunk
  cat(knitr::knit(text = knitr::knit_expand(text = sub_chunk), quiet = TRUE))
}
```

# Data

```{r selected.oligos, include=FALSE}
#Extract the selected oligonucleotides names to print as a comma separated string
if (length(selected.oligos.db()) > 1) { #if more than one oligo, then use plural
  selected.oligos <- paste("oligonucleotides", paste(selected.oligos.db()[1:length(selected.oligos.db())-1], collapse=", "), "and", selected.oligos.db()[length(selected.oligos.db())])
} else { #else use singular 
  selected.oligos <- paste("oligonucleotide", paste(selected.oligos.db(), collapse=", "))
}
```

This report was generated by *g4dbr* for the `r selected.oligos` on `r Sys.Date()`.

```{r title, include=FALSE}
#Document title takes selected oligonucleotides values
title_var <- paste(paste(selected.oligos.db(), collapse="/"), "report")
```

---
title: `r title_var`
author: g4dbr
date: `r Sys.Date()`
output:
word_document:
reference_docx: word-styles-reference.docx
---


```{r oligo.table, echo=FALSE, message=FALSE, warning=FALSE, paged.print=TRUE}
#table of oligonucleotides properties (pageable)
db.info <- db.info() %>%
  filter(oligo %in% selected.oligos.db()) %>% #only display selected oligos data
  select(c('oligo', 'sequence', 'submitted_by', 'depo.date', 'DOI'))

knitr::kable(db.info,
             caption = 'General oligonucleotide information',
             escape = F) #DOI parsed in HTML reports
```


# Figures


## CD


```{r CDplot, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
if (length(selected.oligos.db()) > 1) {
  subchunkify(g = p.CD.db() +
                theme(legend.position = 'bottom',
                      legend.title = element_text(size = 8),
                      legend.title = element_text(size = 9)), #plot
              cap = "paste('Circular dichroism spectra of', paste('the', paste(selected.oligos.db()[1:length(selected.oligos.db())-1], collapse=', '), 'and', selected.oligos.db()[length(selected.oligos.db())]), 'oligonucleotides')", #figure caption
              fig_height = 2.5 * row.p.CD.db(), #dynamic figure height
              fig_width = (8*col.p.CD.db())/(col.p.CD.db()+0.5) #dynamic figure width
  ) 
} else {
  subchunkify(g = p.CD.db()+
                theme(legend.position = 'bottom',
                      legend.title = element_text(size = 8),
                      legend.title = element_text(size = 9)), 
              cap = "paste('Circular dichroism spectra of', paste('the', paste(selected.oligos.db(), collapse=', ', 'oligonucleotide')))",
              fig_height = 2.5 * row.p.CD.db(), #dynamic figure height
              fig_width = (8*col.p.CD.db())/(col.p.CD.db()+0.5) #dynamic figure width
  )
}

```


## 1H-NMR


```{r NMRplot, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
# pnmr <- p.NMR.db()
# subchunkify(pnmr, 2.5 * row.p.NMR.db(), (9*col.p.NMR.db())/(col.p.NMR.db()+0.4)) #figure height based on number of figure rows in the app

if (length(selected.oligos.db()) > 1) {
  subchunkify(g = p.NMR.db()+
                theme(legend.position = 'bottom',
                      legend.title = element_text(size = 8),
                      legend.title = element_text(size = 9)), #plot
              cap = "paste('NMR spectra of', paste('the', paste(selected.oligos.db()[1:length(selected.oligos.db())-1], collapse=', '), 'and', selected.oligos.db()[length(selected.oligos.db())]), 'oligonucleotides')", #figure caption
              fig_height = 2.5 * row.p.NMR.db(), #dynamic figure height
              fig_width = (9*col.p.NMR.db())/(col.p.NMR.db()+0.4) #dynamic figure width
  ) 
} else {
  subchunkify(g = p.NMR.db()+
                theme(legend.position = 'bottom',
                      legend.title = element_text(size = 8),
                      legend.title = element_text(size = 9)), 
              cap = "paste('NMR spectrum of', paste('the', paste(selected.oligos.db(), collapse=', ', 'oligonucleotide')))",
              fig_height = 2.5 * row.p.NMR.db(), #dynamic figure height
              fig_width = (9*col.p.NMR.db())/(col.p.NMR.db()+0.4) #dynamic figure width
  )
}

```


## UV-melting


### Raw data


```{r UVplot.fit, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
puf <- p.UV.fit.db() + 
  guides(colour=guide_legend(nrow=length(selected.oligos.db())),
         ncol = 3) +
  theme(legend.position = 'bottom',
        legend.title = element_text(size = 8),
        legend.title = element_text(size = 9))

if (length(selected.oligos.db()) > 1) {
  subchunkify(g = puf, #plot
              cap = "paste('Folded fraction from UV-melting experiments of', paste('the', paste(selected.oligos.db()[1:length(selected.oligos.db())-1], collapse=', '), 'and', selected.oligos.db()[length(selected.oligos.db())]), 'oligonucleotides')", #figure caption
              fig_height = 4,
              fig_width = 6
  ) 
} else {
  subchunkify(g = puf, 
              cap = "paste('Folded fraction from UV-melting experiments of', paste('the', paste(selected.oligos.db(), collapse=', ', 'oligonucleotide')))",
              fig_height = 4,
              fig_width = 6
  )
}

```


### Processed data


```{r UVplot.raw, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
puv <- p.UV.melting.db() + 
  guides(colour=guide_legend(nrow=length(selected.oligos.db())),
         ncol = 3) +
  theme(legend.position = 'bottom',
        legend.title = element_text(size = 8),
        legend.title = element_text(size = 9))

if (length(selected.oligos.db()) > 1) {
  subchunkify(g = puv, #plot
              cap = "paste('Raw UV-melting plots of', paste('the', paste(selected.oligos.db()[1:length(selected.oligos.db())-1], collapse=', '), 'and', selected.oligos.db()[length(selected.oligos.db())]), 'oligonucleotides')", #figure caption
              fig_height = 4,
              fig_width = 6
  ) 
} else {
  subchunkify(g = puv, 
              cap = "paste('Raw UV-melting plots of', paste('the', paste(selected.oligos.db(), collapse=', ', 'oligonucleotide')))",
              fig_height = 4,
              fig_width = 6
  )
}


```


```{r print.option, message=FALSE, warning=FALSE, include=FALSE}
#controls whether MS section is knitted or not based on the use of the plotMS button
if(input$plotMS.db == 0) {
  print.option <- FALSE
} else {
  print.option <- TRUE
}
```


```{r MS.header, echo=FALSE, eval= print.option}
#conditional MS section title
asis_output("## Native ESI-MS")
```


```{r MSplot, eval=print.option, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
pms <- p.MS.db() + 
  theme(legend.position="bottom",
        legend.direction = 'horizontal',
        legend.title = element_text(size = 8),
        legend.title = element_text(size = 9))

if (length(selected.oligos.db()) > 1) {
  subchunkify(g = pms, #plot
              cap = "paste('Native MS spectra of', paste('the', paste(selected.oligos.db()[1:length(selected.oligos.db())-1], collapse=', '), 'and', selected.oligos.db()[length(selected.oligos.db())]), 'oligonucleotides')", #figure caption
              fig_height = 3 * row.p.MS.db(), #dynamic figure heights
              fig_width = (9*col.p.MS.db())/(col.p.MS.db()+0.4) #dynamic figure width
  ) 
} else {
  subchunkify(g = pms, 
              cap = "paste('Native MS spectra of', paste('the', paste(selected.oligos.db(), collapse=', ', 'oligonucleotide')))",
              fig_height = 3 * row.p.MS.db(), #dynamic figure height
              fig_width = (9*col.p.MS.db())/(col.p.MS.db()+0.4) #dynamic figure width
  )
}

```


